# This configuration file updates the default configuration file
# See https://github.com/searxng/searxng/blob/master/searx/botdetection/limiter.toml

[botdetection.ip_limit]
# Disable link_token â€” API calls from backend don't have browser tokens
link_token = false

[botdetection.ip_lists]
# Allow Railway internal network
pass_ip = ["100.64.0.0/10", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
